### ISSUE TITLE
hand_right_finger_upper_joint vs. hand_right_finger_upper_link

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_motion_planner#11]
Hi,
rviz gives me the error in RobotModel, that no that
```
No transform from [hand_left_finger_uppper_link] to [map]
```
Grepping through the complete project, I get e.g.
```
squirrel_motion_planner/squirrel_8dof_planner/config/robotino_plan.urdf:  <link name="hand_right_finger_upper_link">
```
and
```
squirrel_motion_planner/squirrel_8dof_planner/config/robotino_plan.srdf:    <passive_joint name="hand_right_finger_upper_joint" />
```
Somehow these names have changed. Maybe KCL did.
Which ones are correct?

**Comment by NadiaHG** [comment]
I am sorry I don't understand the question. 

Both are rights, you have a link and a joint with the name:  ` hand_right_finger_upper_*`

I didn't create the files: `squirrel_motion_planner/squirrel_8dof_planner/config/robotino_plan.urdf` and `squirrel_motion_planner/squirrel_8dof_planner/config/robotino_plan.srdf` . But I believe ( and really really hope!!! ) this URDF was only used to generate the moveit configuration and is not being loaded as robot_description. 

Theoretically the RVIZ error is about the robot_description or/and the tf ( joint_states) of the robot, there is not transformation between the hand_left_finger_upper_link and the map.  

- robot_description:
I checked my last robot description ( https://github.com/squirrel-project/squirrel_robotino/blob/indigo_dev/robotino_bringup/robots/tuw-robotino2/urdf/robotino.urdf.xacro ) and the urdf tree is right ( I loaded the model and used robot_state_publisher and joint_state_publisher to verify that the tf tree is connected). 
- tf (joint_states):
If you are only having the error for this link I can image that the driver which should publish the joint_states of the hand is not working properly, did you check the joint_states output??

**Comment by mzillich** [comment]
OK, then I think that it is the latter case, i.e. joint_states with the correct names are not published. I will check that. thanks!
